build: fix configure failure in gcc-14
```
$ ./configure
…
Checking for opendir/readdir/closedir/dirent.h/stdint.h... no
!! Some required functionality is not available. See config.log for details.
…
$ cat config.log
.config.c:12:9: error: implicit declaration of function ‘puts’ [-Wimplicit-function-declaration]
// once the right prototype is in view:
.config.c:13:27: error: passing argument 1 of ‘puts’ makes pointer from integer without a cast [-Wint-conversion]
```